name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "3 3 * * 2" # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip ci]')
    name: macOS (Swift 6.3)
    runs-on: macos-26
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Select Xcode 26.6 (Swift 6.3)
        run: sudo xcode-select -s /Applications/Xcode_26.6.app

      - name: Disable SwiftSyntax Prebuilts
        run: |
          defaults write com.apple.dt.Xcode IDEPackageEnablePrebuilts -bool NO

          # nuke cache to ensure it takes effect
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Developer/Xcode/SourcePackages
          rm -rf ~/Library/Caches/org.swift.swiftpm

      - name: Build
        run: |
          swift --version
          swift build
